### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by stwiname** [subquery/subql-ai-app-framework#1]
## Description

This issue tracks any outstanding tasks needed to get towards a production release

## TODOs

- [x] Setup CI for testing
- [x] Setup publishing and CI workflow
- [x] Documentation
- [x] Project init command
- [ ] Fix build issues with embeddings generation from markdown
- [x] Limit/make more configurable Deno permissions and webworker permissions
- [ ] Improve error handling
